# Default values for redis-stateful
replicaCount: 1

image:
  repository: sergeisin/redis-stateful
  tag: "c88898843492cb88f5fb49bb5bb80e8480fc40d4"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379
  headless:
    enabled: true

persistence:
  enabled: true
  storageClass: ""  # Use default storage class
  size: 1Gi
  accessMode: ReadWriteOnce

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Exposure options
exposure:
  type: "ingress"  # nodeport or ingress
  nodePort: 30379
