apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-stateful
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SergeiMuhin/Gitopsexample
    targetRevision: HEAD
    path: helm-chart/redis-stateful
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
