apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "redis-stateful.fullname" . }}
  labels:
    {{- include "redis-stateful.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "redis-stateful.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "redis-stateful.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "redis-stateful.selectorLabels" . | nindent 8 }}
    spec:
      # Optional security context (uncomment for production)
      # securityContext:
      #   runAsNonRoot: true
      #   runAsUser: 999
      #   fsGroup: 999
      containers:
      - name: redis
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        # Optional security context (uncomment for production)
        # securityContext:
        #   allowPrivilegeEscalation: false
        #   readOnlyRootFilesystem: true
        #   capabilities:
        #     drop: [ALL]
        ports:
        - containerPort: 6379
          name: redis
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        readinessProbe:
          exec:
            command: ["redis-cli", "ping"]
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: redis-data
          mountPath: /data
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "{{ .Values.persistence.accessMode }}" ]
      {{- if .Values.persistence.storageClass }}
      storageClassName: {{ .Values.persistence.storageClass }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
  {{- end }}
